export type MinTrack = "junior" | "mid" | "senior";

export type GlossaryEntry = {
  term: string;
  definition: string;
  minTrack: MinTrack;
};

export const GLOSSARY_ENTRIES: GlossaryEntry[] = [
  {
    term: "Closure",
    definition: "Función que recuerda variables de su scope de creación.",
    minTrack: "junior",
  },
  {
    term: "Specificity",
    definition: "Peso de un selector CSS para resolver conflictos.",
    minTrack: "junior",
  },
  // JS / TS fundamentals
  { term: "Scope", definition: "Región donde un identificador (variable/función) es visible.", minTrack: "junior" },
  { term: "Lexical scope", definition: "Scope determinado por la posición del código (no por el call stack).", minTrack: "junior" },
  { term: "Hoisting", definition: "Efecto por el que ciertas declaraciones quedan disponibles antes en el scope (con matices).", minTrack: "junior" },
  { term: "Temporal Dead Zone (TDZ)", definition: "Zona donde `let/const` existen pero no se pueden usar antes de inicializar.", minTrack: "mid" },
  { term: "Immutability", definition: "No mutar datos existentes; crear copias con cambios para evitar efectos colaterales.", minTrack: "junior" },
  { term: "Mutation", definition: "Cambio in-place de un objeto/array; suele dificultar debug y memoización.", minTrack: "junior" },
  { term: "Pure function", definition: "Sin side effects: mismo input → mismo output.", minTrack: "junior" },
  { term: "Side effect", definition: "Acción observable fuera de la función: I/O, mutación global, tiempo, red.", minTrack: "junior" },
  { term: "Referential equality", definition: "Dos referencias apuntan al mismo objeto (`a === b`).", minTrack: "junior" },
  { term: "Structural equality", definition: "Dos valores tienen el mismo contenido/estructura (no necesariamente misma referencia).", minTrack: "mid" },
  { term: "Idempotency", definition: "Repetir una operación produce el mismo estado final (útil en APIs).", minTrack: "mid" },
  { term: "Race condition", definition: "Resultado depende del orden/tiempo de operaciones concurrentes.", minTrack: "mid" },
  { term: "Event loop", definition: "Mecanismo que ejecuta tareas async en JS (macrotasks/microtasks).", minTrack: "mid" },
  { term: "Microtask", definition: "Cola de tareas de alta prioridad (Promises) que corre antes que timers.", minTrack: "mid" },
  { term: "Macrotask", definition: "Tareas como `setTimeout`, I/O; corren después de microtasks.", minTrack: "mid" },
  { term: "Promise", definition: "Representa un resultado futuro (resolve/reject).", minTrack: "junior" },
  { term: "Async/await", definition: "Sintaxis para trabajar con Promises de forma secuencial.", minTrack: "junior" },
  { term: "Type narrowing", definition: "Reducir un union type usando checks (`typeof`, `in`, discriminants).", minTrack: "mid" },
  { term: "Discriminated union", definition: "Union con un campo literal común (ej. `kind`) para control de flujo.", minTrack: "mid" },
  { term: "Type predicate", definition: "Función que informa a TS sobre el tipo: `x is T`.", minTrack: "mid" },
  { term: "Assertion function", definition: "Función `asserts condition` que ayuda a TS y puede throw en runtime.", minTrack: "mid" },
  { term: "Generics", definition: "Tipos parametrizados para reutilizar funciones/estructuras sin perder info de tipos.", minTrack: "mid" },
  { term: "Inference", definition: "TS deduce tipos a partir del contexto (sin anotarlos explícitamente).", minTrack: "mid" },
  { term: "Literal type", definition: "Tipo más específico: `'a'`, `42`, `true`.", minTrack: "mid" },
  { term: "Union type", definition: "Un valor puede ser uno de varios tipos: `A | B`.", minTrack: "junior" },
  { term: "Intersection type", definition: "Combina tipos: `A & B` (debe cumplir ambos).", minTrack: "mid" },
  { term: "Index signature", definition: "Describe objetos con keys dinámicas: `{ [k: string]: T }`.", minTrack: "mid" },
  { term: "Mapped type", definition: "Construye tipos a partir de keys: `Pick`, `Partial`, `Record`.", minTrack: "mid" },
  { term: "Conditional type", definition: "Tipo que depende de una condición: `T extends U ? X : Y`.", minTrack: "senior" },
  { term: "Template literal types", definition: "Tipos basados en strings: `` `${A}-${B}` ``.", minTrack: "senior" },
  { term: "Never", definition: "Tipo para valores imposibles; útil para exhaustividad.", minTrack: "mid" },
  { term: "Unknown", definition: "Tipo seguro para datos externos; requiere narrowing antes de usar.", minTrack: "mid" },
  { term: "Any", definition: "Desactiva chequeos de tipo; aumenta riesgo de bugs.", minTrack: "junior" },
  { term: "Type alias vs interface", definition: "Alias para tipos compuestos; interface para shapes extensibles (ambos útiles).", minTrack: "mid" },
  { term: "Duck typing", definition: "Si tiene la forma, sirve; TS es estructural, no nominal.", minTrack: "mid" },
  { term: "Nominal typing", definition: "El tipo depende de la identidad (no solo la estructura); no es TS por defecto.", minTrack: "senior" },

  // React / frontend
  { term: "Component", definition: "Unidad reutilizable de UI (función que retorna UI).", minTrack: "junior" },
  { term: "Props", definition: "Inputs de un componente; vienen del padre y no se deberían mutar.", minTrack: "junior" },
  { term: "State", definition: "Datos internos del componente que cambian en el tiempo.", minTrack: "junior" },
  { term: "Derived state", definition: "Estado calculable a partir de props/otros estados; duplicarlo suele ser un smell.", minTrack: "mid" },
  { term: "Controlled input", definition: "Input cuyo valor viene de state + `onChange` actualiza state.", minTrack: "junior" },
  { term: "Uncontrolled input", definition: "Input donde el DOM mantiene el valor (refs); útil en casos puntuales.", minTrack: "mid" },
  { term: "Hook", definition: "API de React para usar estado/efectos/composición en funciones.", minTrack: "junior" },
  { term: "useEffect", definition: "Sincroniza con el mundo externo (timers, subscripciones, fetch).", minTrack: "junior" },
  { term: "Dependency array", definition: "Lista que controla cuándo re-ejecuta un effect/memo/callback.", minTrack: "junior" },
  { term: "Cleanup", definition: "Función de `useEffect` para desuscribir/cancelar timers al unmount/cambio.", minTrack: "mid" },
  { term: "useMemo", definition: "Memoiza el resultado de una computación para evitar recomputación.", minTrack: "mid" },
  { term: "useCallback", definition: "Memoiza una función para pasar referencias estables a hijos.", minTrack: "mid" },
  { term: "React.memo", definition: "Evita re-render si props no cambian (por comparación shallow por defecto).", minTrack: "mid" },
  { term: "Re-render", definition: "React vuelve a ejecutar el componente para producir nuevo UI.", minTrack: "junior" },
  { term: "Reconciliation", definition: "React compara árboles para aplicar cambios mínimos al DOM.", minTrack: "mid" },
  { term: "Key", definition: "Identificador estable para listas; evita bugs al reordenar/filtrar.", minTrack: "junior" },
  { term: "Context", definition: "Mecanismo para compartir valores sin prop drilling.", minTrack: "mid" },
  { term: "Prop drilling", definition: "Pasar props por muchos niveles solo para llegar a un hijo.", minTrack: "junior" },
  { term: "Suspense", definition: "Patrón de React para esperar recursos y renderizar fallback.", minTrack: "senior" },
  { term: "Hydration", definition: "Adjuntar JS y handlers al HTML SSR para volverlo interactivo.", minTrack: "mid" },
  { term: "SSR", definition: "Renderizar HTML en server para mejorar first paint y SEO.", minTrack: "junior" },
  { term: "CSR", definition: "Renderizar mayormente en el cliente (SPA-like).", minTrack: "junior" },
  { term: "SSG", definition: "Generar páginas estáticas en build; muy rápido y cacheable.", minTrack: "mid" },
  { term: "ISR", definition: "Regeneración incremental: SSG + refresh en background.", minTrack: "senior" },
  { term: "RSC", definition: "React Server Components: componentes que corren en server (no se envían al cliente).", minTrack: "senior" },

  // Web fundamentals
  { term: "HTTP", definition: "Protocolo request/response entre cliente y servidor.", minTrack: "junior" },
  { term: "Status code", definition: "Código HTTP (200, 401, 404, 500) que indica el resultado de un request.", minTrack: "junior" },
  { term: "Headers", definition: "Metadata del request/response (content-type, cache-control, etc.).", minTrack: "junior" },
  { term: "Cache-Control", definition: "Header que define cacheabilidad y revalidación.", minTrack: "mid" },
  { term: "ETag", definition: "Identificador de versión de recurso para caching condicional.", minTrack: "senior" },
  { term: "CORS", definition: "Política del navegador que controla requests cross-origin.", minTrack: "mid" },
  { term: "SameSite cookie", definition: "Atributo que restringe envío de cookies entre sitios; mitiga CSRF.", minTrack: "mid" },
  { term: "CSRF", definition: "Ataque donde un sitio induce requests autenticados del usuario sin intención.", minTrack: "mid" },
  { term: "XSS", definition: "Inyección de scripts; se mitiga con escaping, CSP, sanitización.", minTrack: "mid" },
  { term: "CSP", definition: "Content Security Policy: restringe fuentes de scripts/estilos para mitigar XSS.", minTrack: "senior" },
  { term: "JWT", definition: "Token firmado (no encriptado por defecto); cuidado con expiración/rotación.", minTrack: "mid" },
  { term: "Session", definition: "Estado de autenticación (habitualmente cookie + server o JWT).", minTrack: "junior" },
  { term: "OAuth", definition: "Protocolo de autorización delegada (login con Google/GitHub, etc.).", minTrack: "senior" },
  { term: "OpenID Connect", definition: "Capa de identidad sobre OAuth2 para login.", minTrack: "senior" },

  // CSS / UI
  { term: "Cascade", definition: "Reglas para resolver conflictos CSS: origen, importancia, especificidad, orden.", minTrack: "junior" },
  { term: "Box model", definition: "Modelo de caja: content, padding, border, margin.", minTrack: "junior" },
  { term: "Stacking context", definition: "Reglas que controlan apilamiento (z-index) y composición.", minTrack: "mid" },
  { term: "Flexbox", definition: "Layout 1D (fila/columna) para alinear y distribuir espacio.", minTrack: "junior" },
  { term: "CSS Grid", definition: "Layout 2D (filas y columnas) para estructuras complejas.", minTrack: "junior" },
  { term: "Responsive design", definition: "Diseño que se adapta a tamaños y capacidades del dispositivo.", minTrack: "junior" },
  { term: "Breakpoint", definition: "Punto donde cambia el layout según ancho (media queries).", minTrack: "junior" },
  { term: "Design token", definition: "Valor reutilizable (color, spacing) centralizado para consistencia.", minTrack: "mid" },
  { term: "Accessibility (a11y)", definition: "Diseño/implementación para que más personas puedan usar la UI.", minTrack: "junior" },
  { term: "Semantic HTML", definition: "Usar tags con significado (`button`, `nav`, `main`) para estructura/a11y.", minTrack: "junior" },
  { term: "ARIA", definition: "Atributos de accesibilidad para casos donde HTML semántico no alcanza.", minTrack: "mid" },
  { term: "Focus ring", definition: "Indicador visible del foco de teclado; clave para accesibilidad.", minTrack: "junior" },
  { term: "Contrast ratio", definition: "Relación de contraste texto/fondo; afecta legibilidad (WCAG).", minTrack: "mid" },

  // Testing
  { term: "Unit test", definition: "Test de una unidad pequeña (función) con dependencias aisladas.", minTrack: "junior" },
  { term: "Integration test", definition: "Test que cubre interacción entre partes (sin ser end-to-end completo).", minTrack: "mid" },
  { term: "E2E test", definition: "Test end-to-end: simula usuario real y sistema completo.", minTrack: "mid" },
  { term: "Mock", definition: "Sustituto controlado de una dependencia (I/O) para testear en aislamiento.", minTrack: "junior" },
  { term: "Stub", definition: "Implementación mínima que devuelve valores fijos.", minTrack: "mid" },
  { term: "Spy", definition: "Registro de llamadas para aserciones (cuántas veces, con qué args).", minTrack: "mid" },
  { term: "Flaky test", definition: "Test que falla intermitentemente sin cambios en código.", minTrack: "mid" },
  { term: "Arrange-Act-Assert", definition: "Estructura de test: preparar, ejecutar, verificar.", minTrack: "junior" },

  // Performance / ops
  { term: "TTFB", definition: "Time To First Byte: tiempo hasta el primer byte del response.", minTrack: "mid" },
  { term: "LCP", definition: "Largest Contentful Paint: métrica de carga percibida.", minTrack: "mid" },
  { term: "CLS", definition: "Cumulative Layout Shift: cambios de layout inesperados.", minTrack: "mid" },
  { term: "Tree shaking", definition: "Eliminar código no usado en build (bundlers).", minTrack: "mid" },
  { term: "Code splitting", definition: "Dividir bundle para cargar solo lo necesario por ruta.", minTrack: "mid" },
  { term: "Observability", definition: "Entender el sistema con logs, métricas y traces.", minTrack: "senior" },
  { term: "Tracing", definition: "Seguir una request a través de servicios (spans) para diagnosticar latencia.", minTrack: "senior" },
  { term: "SLO / SLA", definition: "Objetivos/garantías de servicio (disponibilidad, latencia).", minTrack: "senior" },
  { term: "Cache invalidation", definition: "Decidir cuándo invalidar/refresh cache; fuente clásica de bugs.", minTrack: "senior" },

  // Git / tooling
  { term: "Commit", definition: "Snapshot de cambios en Git con un mensaje.", minTrack: "junior" },
  { term: "Branch", definition: "Línea de trabajo aislada en Git.", minTrack: "junior" },
  { term: "Merge", definition: "Integrar cambios de una rama en otra.", minTrack: "junior" },
  { term: "Rebase", definition: "Reaplicar commits sobre otra base para un historial lineal.", minTrack: "mid" },
  { term: "Conflict", definition: "Cuando Git no puede resolver automáticamente cambios en las mismas líneas.", minTrack: "junior" },
  { term: "Cherry-pick", definition: "Traer un commit específico a otra rama.", minTrack: "mid" },
  { term: "Squash", definition: "Combinar varios commits en uno.", minTrack: "mid" },
  { term: "CI", definition: "Integración continua: correr builds/tests/lints en cada cambio.", minTrack: "junior" },
  { term: "CD", definition: "Entrega/despliegue continuo: automatizar deploys.", minTrack: "mid" },
  { term: "Lint", definition: "Reglas automáticas para estilo y errores comunes.", minTrack: "junior" },
  { term: "Formatter", definition: "Herramienta que formatea código de forma consistente (ej. Prettier).", minTrack: "junior" },
  { term: "Bundle", definition: "Archivo(s) generado(s) para shipping en web (JS/CSS).", minTrack: "junior" },
  { term: "Bundler", definition: "Herramienta que empaqueta dependencias (Vite/Webpack/Rollup).", minTrack: "mid" },
  { term: "Source map", definition: "Mapa para debugear código minificado desde el original.", minTrack: "mid" },
  { term: "Minification", definition: "Reducir tamaño del código (rename, eliminar whitespace).", minTrack: "mid" },
  { term: "Polyfill", definition: "Implementación para soportar APIs faltantes en navegadores viejos.", minTrack: "mid" },

  // Networking / APIs
  { term: "REST", definition: "Estilo de API basado en recursos y métodos HTTP.", minTrack: "junior" },
  { term: "GraphQL", definition: "Lenguaje de query para APIs; el cliente define qué fields necesita.", minTrack: "mid" },
  { term: "RPC", definition: "Llamadas a procedimientos remotos; se invoca como función.", minTrack: "mid" },
  { term: "Pagination", definition: "Dividir resultados en páginas (offset/limit o cursor).", minTrack: "junior" },
  { term: "Cursor pagination", definition: "Paginación basada en cursor; estable bajo inserts.", minTrack: "senior" },
  { term: "Rate limit", definition: "Límite de requests en una ventana para evitar abuso/carga.", minTrack: "mid" },
  { term: "Retry-After", definition: "Header que indica cuándo reintentar tras 429/503.", minTrack: "mid" },
  { term: "Timeout", definition: "Cortar una operación si supera un tiempo límite.", minTrack: "junior" },
  { term: "Circuit breaker", definition: "Patrón: cortar requests a un servicio fallando para recuperarse.", minTrack: "senior" },

  // Data / storage
  { term: "Normalization (data)", definition: "Evitar duplicación y mantener consistencia en modelos de datos.", minTrack: "mid" },
  { term: "Denormalization", definition: "Duplicar datos por performance/consultas; requiere estrategia de sync.", minTrack: "senior" },
  { term: "Index", definition: "Estructura para acelerar consultas en DB (a costa de escritura/espacio).", minTrack: "mid" },
  { term: "Schema", definition: "Estructura esperada de datos (campos/tipos/restricciones).", minTrack: "junior" },
  { term: "Migration", definition: "Cambio versionado del esquema o datos en DB.", minTrack: "mid" },
  { term: "Transaction", definition: "Conjunto de operaciones atómicas: all-or-nothing.", minTrack: "senior" },
  { term: "Consistency", definition: "Garantías sobre el estado de datos (fuerte vs eventual).", minTrack: "senior" },
  { term: "Eventual consistency", definition: "El estado converge con el tiempo; puede haber lecturas desactualizadas.", minTrack: "senior" },
  { term: "Lock", definition: "Mecanismo para evitar escrituras concurrentes conflictivas.", minTrack: "senior" },
  { term: "Optimistic concurrency", definition: "Detectar conflictos por versión/etag y reintentar.", minTrack: "senior" },

  // Security deeper
  { term: "Authentication", definition: "Probar quién sos (login).", minTrack: "junior" },
  { term: "Authorization", definition: "Probar qué podés hacer (permisos).", minTrack: "junior" },
  { term: "Least privilege", definition: "Dar el mínimo acceso necesario.", minTrack: "mid" },
  { term: "Secret", definition: "Valor sensible (keys/tokens) que no debe quedar en repos/logs.", minTrack: "junior" },
  { term: "Rotation", definition: "Cambiar secrets periódicamente para reducir impacto de leaks.", minTrack: "senior" },
  { term: "Hashing", definition: "Transformación irreversible (passwords con salt+cost).", minTrack: "mid" },
  { term: "Salting", definition: "Agregar aleatoriedad a hashing para evitar rainbow tables.", minTrack: "mid" },
  { term: "Brute force", definition: "Intentar muchas combinaciones (password guessing).", minTrack: "junior" },
  { term: "Credential stuffing", definition: "Probar credenciales filtradas en otros sitios.", minTrack: "mid" },

  // Architecture / design
  { term: "Separation of concerns", definition: "Separar responsabilidades para reducir acoplamiento.", minTrack: "mid" },
  { term: "Single responsibility", definition: "Un módulo debería tener un motivo principal para cambiar.", minTrack: "mid" },
  { term: "Boundary", definition: "Límite entre capas/módulos donde definís contratos.", minTrack: "senior" },
  { term: "API boundary", definition: "Frontera donde validás inputs/outputs y manejás errores.", minTrack: "senior" },
  { term: "Layering", definition: "Organizar en capas (UI, dominio, data) para claridad.", minTrack: "mid" },
  { term: "Dependency inversion", definition: "Depender de abstracciones, no de concreciones.", minTrack: "senior" },
  { term: "Composition over inheritance", definition: "Preferir componer objetos/funciones antes que heredar.", minTrack: "mid" },
  { term: "Invariant", definition: "Condición que debe mantenerse siempre verdadera en un sistema.", minTrack: "mid" },
  { term: "Contract", definition: "Promesa de comportamiento (inputs/outputs/errores) entre componentes.", minTrack: "mid" },
  { term: "Backwards compatibility", definition: "Cambios que no rompen clientes existentes.", minTrack: "mid" },
  { term: "Breaking change", definition: "Cambio incompatible; requiere migración o versionado.", minTrack: "mid" },
  { term: "Versioning", definition: "Estrategia para evolucionar APIs (semver, v1/v2).", minTrack: "senior" },
  { term: "Semantic versioning", definition: "MAJOR.MINOR.PATCH según breaking/feature/fix.", minTrack: "mid" },

  // UX / product
  { term: "Friction", definition: "Costo percibido para completar una tarea (pasos, esfuerzo, confusión).", minTrack: "mid" },
  { term: "Onboarding", definition: "Primeras experiencias para entender y empezar a usar el producto.", minTrack: "mid" },
  { term: "Activation", definition: "Momento en que el usuario obtiene valor real por primera vez.", minTrack: "senior" },
  { term: "Retention", definition: "Capacidad de que usuarios vuelvan con el tiempo.", minTrack: "senior" },
  { term: "Churn", definition: "Usuarios que dejan de usar el producto.", minTrack: "senior" },

  // More high-frequency frontend terms (to reach 200+)
  { term: "Debounce", definition: "Esperar a que pare el input/evento antes de ejecutar (ej. search).", minTrack: "mid" },
  { term: "Throttle", definition: "Ejecutar como máximo una vez cada N ms (limitar frecuencia).", minTrack: "mid" },
  { term: "Jitter", definition: "Aleatoriedad pequeña agregada a delays para evitar picos sincronizados.", minTrack: "senior" },
  { term: "Exponential backoff", definition: "Reintentos con demora creciente (base * factor^i) para reducir carga.", minTrack: "mid" },
  { term: "Retry", definition: "Reintentar una operación ante fallas transitorias.", minTrack: "mid" },
  { term: "Fallback", definition: "Comportamiento alternativo cuando algo falla (UI o datos).", minTrack: "junior" },
  { term: "Graceful degradation", definition: "Funcionar “peor” pero funcional cuando faltan capacidades.", minTrack: "senior" },
  { term: "Progressive enhancement", definition: "Arrancar con base simple y mejorar con capacidades extra.", minTrack: "senior" },
  { term: "Feature detection", definition: "Detectar capacidades del entorno (no inferir por user agent).", minTrack: "mid" },
  { term: "User Agent (UA)", definition: "String del navegador; no es confiable para lógica de producto.", minTrack: "mid" },
  { term: "Telemetry", definition: "Datos de uso/errores enviados para análisis (con privacidad).", minTrack: "senior" },
  { term: "Analytics", definition: "Medición de eventos/métricas de producto (funnels, retención).", minTrack: "mid" },
  { term: "Funnel", definition: "Serie de pasos y su conversión (signup → activation → …).", minTrack: "senior" },
  { term: "A/B test", definition: "Experimento controlado para comparar variantes.", minTrack: "senior" },
  { term: "Cookie", definition: "Dato almacenado por el navegador, usual en sesiones.", minTrack: "junior" },
  { term: "HttpOnly cookie", definition: "Cookie inaccesible desde JS; reduce riesgo en XSS.", minTrack: "mid" },
  { term: "Secure cookie", definition: "Cookie que solo se envía por HTTPS.", minTrack: "mid" },
  { term: "Origin", definition: "Esquema + host + puerto (ej. https://a.com:443).", minTrack: "mid" },
  { term: "Cross-origin", definition: "Entre orígenes distintos; dispara reglas de CORS.", minTrack: "junior" },
  { term: "Same-origin policy", definition: "Reglas del navegador que aíslan orígenes por seguridad.", minTrack: "mid" },
  { term: "URL encoding", definition: "Codificar caracteres en URLs (ej. espacio → %20).", minTrack: "junior" },
  { term: "Percent-encoding", definition: "Forma específica de URL encoding usando %HH.", minTrack: "mid" },
  { term: "Serialization", definition: "Convertir datos a string/bytes (JSON) para transportar/guardar.", minTrack: "junior" },
  { term: "Deserialization", definition: "Reconstruir datos desde string/bytes (JSON.parse).", minTrack: "junior" },
  { term: "Validation", definition: "Verificar que la data cumple un esquema/restricción.", minTrack: "junior" },
  { term: "Sanitization", definition: "Limpiar/escapar inputs para evitar XSS/inyección.", minTrack: "mid" },
  { term: "Canonicalization", definition: "Normalizar representaciones (ej. emails, URLs) a una forma única.", minTrack: "senior" },
  { term: "Localization (l10n)", definition: "Adaptar texto/formatos a un idioma/región.", minTrack: "mid" },
  { term: "Internationalization (i18n)", definition: "Preparar la app para múltiples idiomas/regiones.", minTrack: "mid" },
  { term: "Time zone", definition: "Zona horaria; fuente común de bugs si no se maneja explícitamente.", minTrack: "mid" },
  { term: "UTC", definition: "Referencia estándar de tiempo; útil para guardar timestamps.", minTrack: "junior" },
  { term: "ISO 8601", definition: "Formato de fecha/hora estándar (ej. 2026-04-20T12:34:56Z).", minTrack: "junior" },
  { term: "Monorepo", definition: "Repo con múltiples apps/packages; requiere tooling y convenciones.", minTrack: "senior" },
  { term: "Workspace", definition: "Conjunto de paquetes relacionados (pnpm/yarn workspaces).", minTrack: "senior" },
];

