export type MinTrack = "junior" | "mid" | "senior";

export type SlangEntry = {
  es: string;
  en: string;
  meaning: string;
  minTrack: MinTrack;
};

export const SLANG_ENTRIES: SlangEntry[] = [
  { es: "inestable (test)", en: "flaky", meaning: "Test que a veces falla.", minTrack: "junior" },
  { es: "mezclar ramas", en: "merge", meaning: "Integrar una rama en otra.", minTrack: "junior" },
  { es: "solicitud de cambios", en: "change request", meaning: "Pedido de cambios en PR.", minTrack: "junior" },
  { es: "aprobación", en: "LGTM", meaning: "Looks good to me.", minTrack: "junior" },
  { es: "revisión de código", en: "code review", meaning: "Revisión de un PR/cambio.", minTrack: "junior" },
  { es: "rama principal", en: "main branch", meaning: "Rama principal del repo.", minTrack: "junior" },
  { es: "entorno de pruebas", en: "staging", meaning: "Ambiente previo a producción.", minTrack: "junior" },
  { es: "entorno real", en: "production", meaning: "Ambiente de usuarios reales.", minTrack: "junior" },
  { es: "subir a prod", en: "ship", meaning: "Liberar código a producción.", minTrack: "mid" },
  { es: "parche rápido", en: "hotfix", meaning: "Corrección urgente en prod.", minTrack: "mid" },
  { es: "rollback", en: "rollback", meaning: "Volver a una versión anterior estable.", minTrack: "mid" },
  { es: "incidente", en: "incident", meaning: "Evento que afecta servicio/usuarios.", minTrack: "mid" },
  { es: "guardia", en: "on-call", meaning: "Persona responsable ante incidentes.", minTrack: "mid" },
  { es: "deuda técnica", en: "tech debt", meaning: "Costo futuro por atajos de hoy.", minTrack: "mid" },
  { es: "alcance", en: "scope", meaning: "Qué entra y qué no en una tarea.", minTrack: "junior" },
  { es: "fuera de alcance", en: "out of scope", meaning: "No está incluido en esta entrega.", minTrack: "junior" },
  { es: "estimación", en: "estimate", meaning: "Tiempo/esfuerzo aproximado.", minTrack: "junior" },
  { es: "bloqueado", en: "blocked", meaning: "No puede avanzar por dependencia.", minTrack: "junior" },
  { es: "triage", en: "triage", meaning: "Clasificar/priorizar issues/bugs.", minTrack: "mid" },
  { es: "prioridad", en: "priority", meaning: "Orden de atención de tareas.", minTrack: "junior" },
  { es: "alcanzar paridad", en: "catch up", meaning: "Ponerse al día con cambios.", minTrack: "junior" },
  { es: "hacer seguimiento", en: "follow up", meaning: "Retomar/verificar más tarde.", minTrack: "junior" },
  { es: "perímetro", en: "blast radius", meaning: "Qué tan grande es el impacto de un fallo.", minTrack: "senior" },
  { es: "corte de tráfico", en: "traffic cutover", meaning: "Mover tráfico a otra versión/servicio.", minTrack: "senior" },
  { es: "bandera", en: "feature flag", meaning: "Toggle para habilitar/deshabilitar features.", minTrack: "mid" },
  { es: "lanzamiento gradual", en: "rollout", meaning: "Publicar por etapas.", minTrack: "mid" },
  { es: "prueba en vivo", en: "dogfooding", meaning: "Usar el producto internamente.", minTrack: "mid" },
  { es: "acuerdo de servicio", en: "SLA", meaning: "Garantía de servicio.", minTrack: "senior" },
  { es: "objetivo de servicio", en: "SLO", meaning: "Objetivo medible de confiabilidad.", minTrack: "senior" },
  { es: "presupuesto de error", en: "error budget", meaning: "Margen de fallas tolerables vs SLO.", minTrack: "senior" },
  { es: "postmortem", en: "postmortem", meaning: "Análisis después de un incidente.", minTrack: "senior" },
  { es: "mitigación", en: "mitigation", meaning: "Reducir impacto sin root cause definitiva.", minTrack: "mid" },
  { es: "causa raíz", en: "root cause", meaning: "Motivo fundamental del problema.", minTrack: "mid" },
  { es: "reproducir", en: "repro", meaning: "Pasos para reproducir un bug.", minTrack: "junior" },
  { es: "pasos mínimos", en: "minimal repro", meaning: "Caso mínimo que reproduce el bug.", minTrack: "mid" },
  { es: "regresión", en: "regression", meaning: "Bug que reaparece por un cambio nuevo.", minTrack: "mid" },
  { es: "cierto", en: "true positive", meaning: "Alerta/bug real.", minTrack: "mid" },
  { es: "falso", en: "false positive", meaning: "Alerta incorrecta.", minTrack: "mid" },
  { es: "ruido", en: "noise", meaning: "Señales/alertas no accionables.", minTrack: "mid" },
  { es: "acuerdo de interfaz", en: "contract", meaning: "Lo que un API promete (inputs/outputs).", minTrack: "mid" },
  { es: "cambio que rompe", en: "breaking change", meaning: "Cambio incompatible hacia atrás.", minTrack: "mid" },
  { es: "compatibilidad", en: "backward compatible", meaning: "No rompe a clientes existentes.", minTrack: "mid" },
  { es: "acoplamiento", en: "coupling", meaning: "Dependencia fuerte entre módulos.", minTrack: "senior" },
  { es: "cohesión", en: "cohesion", meaning: "Qué tan relacionado está lo que hace un módulo.", minTrack: "senior" },
  { es: "arreglo temporal", en: "workaround", meaning: "Solución no ideal.", minTrack: "senior" },

  // Common daily engineering vocabulary (frequent in tickets/PRs)
  { es: "a primera vista", en: "at a glance", meaning: "Rápidamente / sin mucho detalle.", minTrack: "junior" },
  { es: "a nivel alto", en: "high-level", meaning: "Sin entrar en detalles de implementación.", minTrack: "junior" },
  { es: "a nivel bajo", en: "low-level", meaning: "Detalles finos de implementación.", minTrack: "junior" },
  { es: "supuesto", en: "assumption", meaning: "Algo que asumimos como cierto para avanzar.", minTrack: "junior" },
  { es: "trade-off", en: "trade-off", meaning: "Intercambio: mejorar X empeora Y.", minTrack: "mid" },
  { es: "punto de corte", en: "cutoff", meaning: "Umbral/límite (fecha, valor).", minTrack: "mid" },
  { es: "caso borde", en: "edge case", meaning: "Caso poco común que rompe lógica.", minTrack: "junior" },
  { es: "caso feliz", en: "happy path", meaning: "Flujo normal sin errores.", minTrack: "junior" },
  { es: "caso negativo", en: "negative case", meaning: "Flujo con error/entrada inválida.", minTrack: "junior" },
  { es: "a mano", en: "manually", meaning: "Hecho manualmente, no automático.", minTrack: "junior" },
  { es: "automatizar", en: "automate", meaning: "Pasar a script/CI para repetir confiable.", minTrack: "junior" },
  { es: "revisar rápido", en: "quick check", meaning: "Chequeo corto para asegurar que no se rompe.", minTrack: "junior" },
  { es: "sanity check", en: "sanity check", meaning: "Chequeo básico de que funciona.", minTrack: "mid" },
  { es: "resumen", en: "summary", meaning: "Síntesis de cambios o estado.", minTrack: "junior" },
  { es: "plan de pruebas", en: "test plan", meaning: "Cómo verificar que el cambio funciona.", minTrack: "junior" },
  { es: "pasar QA", en: "QA pass", meaning: "Validación de calidad (manual o automática).", minTrack: "mid" },
  { es: "lista de chequeo", en: "checklist", meaning: "Items a verificar antes de merge/deploy.", minTrack: "junior" },
  { es: "bajar prioridad", en: "deprioritize", meaning: "Mover algo más abajo en prioridad.", minTrack: "mid" },
  { es: "subir prioridad", en: "prioritize", meaning: "Poner algo arriba en prioridad.", minTrack: "junior" },
  { es: "fecha de corte", en: "freeze date", meaning: "Momento donde se congela para release.", minTrack: "mid" },
  { es: "congelamiento", en: "code freeze", meaning: "Se limitan cambios para estabilizar release.", minTrack: "mid" },
  { es: "enviar a revisión", en: "send for review", meaning: "Abrir PR / pedir review.", minTrack: "junior" },
  { es: "apilar PRs", en: "stacked PRs", meaning: "PRs dependientes uno de otro.", minTrack: "senior" },
  { es: "bloquear merge", en: "block merge", meaning: "No permitir merge hasta resolver X.", minTrack: "mid" },
  { es: "mergear", en: "merge", meaning: "Integrar cambios a la rama destino.", minTrack: "junior" },
  { es: "rebasear", en: "rebase", meaning: "Mover commits sobre otra base.", minTrack: "mid" },
  { es: "resuelto", en: "resolved", meaning: "Problema solucionado / conversación cerrada.", minTrack: "junior" },
  { es: "pendiente", en: "pending", meaning: "Aún no terminado / esperando acción.", minTrack: "junior" },
  { es: "en progreso", en: "in progress", meaning: "Actualmente trabajando en eso.", minTrack: "junior" },
  { es: "hecho", en: "done", meaning: "Finalizado.", minTrack: "junior" },
  { es: "a futuro", en: "going forward", meaning: "De ahora en adelante.", minTrack: "mid" },
  { es: "de paso", en: "while we’re here", meaning: "Aprovechando para hacer otra cosa relacionada.", minTrack: "mid" },
  { es: "fuera de horario", en: "after hours", meaning: "Fuera del horario laboral.", minTrack: "mid" },
  { es: "carga", en: "load", meaning: "Tráfico/carga en un sistema.", minTrack: "junior" },
  { es: "cuello de botella", en: "bottleneck", meaning: "Parte que limita performance/throughput.", minTrack: "mid" },
  { es: "latencia", en: "latency", meaning: "Tiempo de respuesta.", minTrack: "junior" },
  { es: "throughput", en: "throughput", meaning: "Cantidad de trabajo por unidad de tiempo.", minTrack: "senior" },
  { es: "pico", en: "spike", meaning: "Pico de tráfico/uso; o tarea exploratoria rápida.", minTrack: "mid" },
  { es: "spike (tarea)", en: "spike", meaning: "Tarea para investigar antes de implementar.", minTrack: "mid" },
  { es: "hardcodear", en: "hardcode", meaning: "Poner un valor fijo en el código.", minTrack: "junior" },
  { es: "parametrizar", en: "parameterize", meaning: "Hacer configurable en vez de fijo.", minTrack: "mid" },
  { es: "feature", en: "feature", meaning: "Funcionalidad para usuario.", minTrack: "junior" },
  { es: "bug", en: "bug", meaning: "Error en comportamiento.", minTrack: "junior" },
  { es: "issue", en: "issue", meaning: "Ticket: bug/feature/tarea.", minTrack: "junior" },
  { es: "incidencia", en: "outage", meaning: "Caída/interrupción de servicio.", minTrack: "mid" },
  { es: "degradación", en: "degradation", meaning: "Servicio funciona peor (latencia/errores).", minTrack: "mid" },
  { es: "devolver 500", en: "500ing", meaning: "Endpoints devolviendo 500 (server error).", minTrack: "mid" },
  { es: "alerta", en: "alert", meaning: "Notificación de monitoreo.", minTrack: "junior" },
  { es: "página", en: "page", meaning: "Aviso de on-call (pager).", minTrack: "mid" },
  { es: "ack", en: "ack", meaning: "Reconocer/aceptar una alerta.", minTrack: "mid" },
  { es: "ruido de alertas", en: "alert fatigue", meaning: "Demasiadas alertas -> se ignoran.", minTrack: "senior" },
  { es: "mitigar", en: "mitigate", meaning: "Reducir impacto rápido.", minTrack: "mid" },
  { es: "parche", en: "patch", meaning: "Cambio pequeño para arreglar algo.", minTrack: "junior" },
  { es: "arreglar", en: "fix", meaning: "Corregir bug.", minTrack: "junior" },
  { es: "work in progress", en: "WIP", meaning: "No listo todavía.", minTrack: "junior" },
  { es: "a confirmar", en: "TBD", meaning: "To be determined.", minTrack: "junior" },
  { es: "a discutir", en: "TBD", meaning: "Pendiente de decisión.", minTrack: "junior" },
  { es: "a revisar", en: "to review", meaning: "Pendiente de revisión.", minTrack: "junior" },
  { es: "en caliente", en: "in prod / live", meaning: "Corriendo en producción.", minTrack: "mid" },
  { es: "en frío", en: "cold path", meaning: "Código que corre poco (ej. setup).", minTrack: "senior" },
  { es: "inicio en frío", en: "cold start", meaning: "Arranque inicial de una función/serverless.", minTrack: "senior" },
  { es: "cortar la sangría", en: "stop the bleeding", meaning: "Primero mitigar, luego investigar root cause.", minTrack: "senior" },
  { es: "poner guard rails", en: "guardrails", meaning: "Protecciones para evitar errores/abuso.", minTrack: "senior" },

  // More very frequent slang (tickets/PRs/dev)
  { es: "no bloqueante", en: "non-blocking", meaning: "No impide avanzar; se puede hacer luego.", minTrack: "junior" },
  { es: "bloqueante", en: "blocking", meaning: "Impide avanzar; hay que resolverlo primero.", minTrack: "junior" },
  { es: "en paralelo", en: "in parallel", meaning: "Trabajar simultáneamente en dos cosas.", minTrack: "junior" },
  { es: "de punta a punta", en: "end-to-end", meaning: "De extremo a extremo (flujo completo).", minTrack: "junior" },
  { es: "rápido y sucio", en: "quick and dirty", meaning: "Solución rápida, no ideal.", minTrack: "mid" },
  { es: "limpiar", en: "cleanup", meaning: "Dejar el código/estado mejor ordenado.", minTrack: "junior" },
  { es: "refactor", en: "refactor", meaning: "Cambiar estructura sin cambiar comportamiento.", minTrack: "junior" },
  { es: "deuda", en: "debt", meaning: "Atajo que genera costo futuro.", minTrack: "mid" },
  { es: "alcance del ticket", en: "ticket scope", meaning: "Qué está incluido en este ticket.", minTrack: "junior" },
  { es: "criterio de aceptación", en: "acceptance criteria", meaning: "Condiciones para considerar terminado.", minTrack: "junior" },
  { es: "definición de hecho", en: "definition of done", meaning: "Checklist para dar por terminada una tarea.", minTrack: "mid" },
  { es: "no reproducible", en: "cannot repro", meaning: "No se puede reproducir el bug.", minTrack: "junior" },
  { es: "reproducible", en: "reproducible", meaning: "Se puede reproducir consistentemente.", minTrack: "junior" },
  { es: "pasos para repro", en: "steps to repro", meaning: "Pasos para reproducir un bug.", minTrack: "junior" },
  { es: "expected vs actual", en: "expected vs actual", meaning: "Qué esperabas vs qué pasó.", minTrack: "junior" },
  { es: "captura", en: "screenshot", meaning: "Imagen del problema.", minTrack: "junior" },
  { es: "grabación", en: "screen recording", meaning: "Video del problema.", minTrack: "junior" },
  { es: "logs", en: "logs", meaning: "Registros para diagnosticar.", minTrack: "junior" },
  { es: "metricas", en: "metrics", meaning: "Mediciones numéricas (latencia, errores).", minTrack: "mid" },
  { es: "trazas", en: "traces", meaning: "Seguimiento de una request entre servicios.", minTrack: "senior" },
  { es: "alertar", en: "alert", meaning: "Notificar por monitoreo.", minTrack: "junior" },
  { es: "escalar", en: "escalate", meaning: "Pedir ayuda o subir severidad.", minTrack: "mid" },
  { es: "sev", en: "sev", meaning: "Severidad (Sev1, Sev2).", minTrack: "mid" },
  { es: "impacto", en: "impact", meaning: "Cuántos usuarios/qué tan grave.", minTrack: "junior" },
  { es: "priorizar", en: "prioritize", meaning: "Poner primero en la lista.", minTrack: "junior" },
  { es: "despriorizar", en: "deprioritize", meaning: "Bajar prioridad.", minTrack: "mid" },
  { es: "cortar alcance", en: "scope cut", meaning: "Reducir alcance para llegar a tiempo.", minTrack: "mid" },
  { es: "timebox", en: "timebox", meaning: "Limitar tiempo para una tarea.", minTrack: "mid" },
  { es: "tradeoff", en: "trade-off", meaning: "Intercambio: mejora X, empeora Y.", minTrack: "mid" },
  { es: "hacer rollout", en: "rollout", meaning: "Publicar gradualmente.", minTrack: "mid" },
  { es: "apagar feature", en: "toggle off", meaning: "Deshabilitar por flag.", minTrack: "mid" },
  { es: "prender feature", en: "toggle on", meaning: "Habilitar por flag.", minTrack: "mid" },
  { es: "flag", en: "flag", meaning: "Feature flag / toggle.", minTrack: "mid" },
  { es: "dark launch", en: "dark launch", meaning: "Deploy sin exponer al usuario.", minTrack: "senior" },
  { es: "gradual", en: "gradual", meaning: "Por etapas.", minTrack: "junior" },
  { es: "canary", en: "canary", meaning: "Release a un % pequeño primero.", minTrack: "senior" },
  { es: "control", en: "control", meaning: "Grupo sin cambios en un experimento.", minTrack: "senior" },
  { es: "variante", en: "variant", meaning: "Versión B en un A/B test.", minTrack: "senior" },
  { es: "experimento", en: "experiment", meaning: "A/B test o prueba controlada.", minTrack: "senior" },
  { es: "stat sig", en: "statistically significant", meaning: "Resultado con significancia estadística.", minTrack: "senior" },
  { es: "palo", en: "spike", meaning: "Tarea exploratoria corta (investigar).", minTrack: "mid" },
  { es: "poC", en: "PoC", meaning: "Proof of concept.", minTrack: "mid" },
  { es: "mvp", en: "MVP", meaning: "Minimum viable product.", minTrack: "junior" },
  { es: "scope creep", en: "scope creep", meaning: "El alcance crece sin control.", minTrack: "mid" },
  { es: "mejoras", en: "polish", meaning: "Pulir UX/detalles.", minTrack: "mid" },
  { es: "perf", en: "perf", meaning: "Performance.", minTrack: "junior" },
  { es: "perf regression", en: "perf regression", meaning: "Empeora performance por un cambio.", minTrack: "mid" },
  { es: "fast path", en: "fast path", meaning: "Camino optimizado/ejecutado frecuentemente.", minTrack: "senior" },
  { es: "slow path", en: "slow path", meaning: "Camino menos común o más pesado.", minTrack: "senior" },
  { es: "bump", en: "bump", meaning: "Subir versión o actualizar dependencia.", minTrack: "mid" },
  { es: "pin", en: "pin", meaning: "Fijar versión para evitar cambios.", minTrack: "mid" },
  { es: "lockfile", en: "lockfile", meaning: "Archivo que fija versions exactas de deps.", minTrack: "mid" },
  { es: "dep", en: "dependency", meaning: "Dependencia.", minTrack: "junior" },
  { es: "break", en: "break", meaning: "Romper compatibilidad/build.", minTrack: "junior" },
  { es: "build roto", en: "broken build", meaning: "CI/build fallando.", minTrack: "junior" },
  { es: "green", en: "green", meaning: "CI pasando.", minTrack: "junior" },
  { es: "red", en: "red", meaning: "CI fallando.", minTrack: "junior" },
  { es: "pasó por CI", en: "CI passed", meaning: "Checks pasaron.", minTrack: "junior" },
  { es: "falló CI", en: "CI failed", meaning: "Checks fallaron.", minTrack: "junior" },
  { es: "flake", en: "flake", meaning: "Falla intermitente (test flaky).", minTrack: "mid" },
  { es: "reintentar", en: "retry", meaning: "Volver a intentar.", minTrack: "junior" },
  { es: "rerun", en: "rerun", meaning: "Correr de nuevo (job/test).", minTrack: "junior" },
  { es: "revertir", en: "revert", meaning: "Deshacer un cambio con un commit inverso.", minTrack: "mid" },
  { es: "bisectar", en: "bisect", meaning: "Encontrar commit que introduce bug (git bisect).", minTrack: "senior" },
  { es: "repro en local", en: "repro locally", meaning: "Reproducir en entorno local.", minTrack: "junior" },
  { es: "en mi máquina funciona", en: "works on my machine", meaning: "Funciona local pero no en prod/CI.", minTrack: "junior" },
  { es: "no rompe nada", en: "should be safe", meaning: "Debería ser seguro/no romper.", minTrack: "junior" },
  { es: "puede romper", en: "risky", meaning: "Puede tener riesgo.", minTrack: "mid" },
  { es: "cobertura", en: "coverage", meaning: "Cobertura de tests.", minTrack: "junior" },
  { es: "gap", en: "gap", meaning: "Falta/laguna.", minTrack: "junior" },
  { es: "al final del día", en: "at the end of the day", meaning: "En resumen / en última instancia.", minTrack: "junior" },
  { es: "quick win", en: "quick win", meaning: "Mejora fácil con impacto rápido.", minTrack: "mid" },
  { es: "nit", en: "nit", meaning: "Comentario menor de estilo en code review.", minTrack: "mid" },
  { es: "nitpicky", en: "nitpicky", meaning: "Muy detallista con cosas menores.", minTrack: "mid" },
  { es: "drive-by", en: "drive-by comment", meaning: "Comentario suelto sin seguimiento.", minTrack: "senior" },
  { es: "toma", en: "take", meaning: "Intento/versión (\"my take\").", minTrack: "mid" },
  { es: "opinionated", en: "opinionated", meaning: "Con decisiones fuertes de estilo/arquitectura.", minTrack: "senior" },
  { es: "no es necesario ahora", en: "not needed right now", meaning: "Se puede postergar.", minTrack: "junior" },
  { es: "lo dejamos para después", en: "we’ll punt", meaning: "Postergar deliberadamente.", minTrack: "senior" },
  { es: "cortar por lo sano", en: "cut our losses", meaning: "Dejar de invertir en algo que no rinde.", minTrack: "senior" },

  // More frequent dev/product slang to reach 200+
  { es: "handoff", en: "handoff", meaning: "Pasar una tarea/feature a otro equipo/persona.", minTrack: "mid" },
  { es: "handover", en: "handover", meaning: "Transición de responsabilidad.", minTrack: "mid" },
  { es: "alinear", en: "align", meaning: "Ponerse de acuerdo en dirección/decisión.", minTrack: "junior" },
  { es: "stakeholders", en: "stakeholders", meaning: "Personas impactadas/interesadas en el producto.", minTrack: "mid" },
  { es: "customer impact", en: "customer impact", meaning: "Impacto en usuarios/clientes.", minTrack: "mid" },
  { es: "regla de oro", en: "golden rule", meaning: "Principio fuerte para decidir.", minTrack: "mid" },
  { es: "hack", en: "hack", meaning: "Solución improvisada (puede ser temporal).", minTrack: "mid" },
  { es: "hacky", en: "hacky", meaning: "Poco elegante; difícil de mantener.", minTrack: "mid" },
  { es: "te lo debo", en: "I owe you", meaning: "Queda pendiente para después.", minTrack: "junior" },
  { es: "compromiso", en: "commitment", meaning: "Compromiso de entrega/fecha.", minTrack: "mid" },
  { es: "deadline", en: "deadline", meaning: "Fecha límite.", minTrack: "junior" },
  { es: "ETA", en: "ETA", meaning: "Estimated time of arrival (cuándo estaría).", minTrack: "junior" },
  { es: "FYI", en: "FYI", meaning: "For your information (solo para informar).", minTrack: "junior" },
  { es: "IMO", en: "IMO", meaning: "In my opinion.", minTrack: "junior" },
  { es: "IIRC", en: "IIRC", meaning: "If I recall correctly.", minTrack: "mid" },
  { es: "TL;DR", en: "TL;DR", meaning: "Resumen corto.", minTrack: "junior" },
  { es: "ping", en: "ping", meaning: "Avisar/recordar a alguien (\"te hago ping\").", minTrack: "junior" },
  { es: "loop in", en: "loop in", meaning: "Sumar a alguien a la conversación.", minTrack: "mid" },
  { es: "heads up", en: "heads up", meaning: "Aviso previo de algo importante.", minTrack: "junior" },
  { es: "FYI-only", en: "FYI-only", meaning: "No requiere acción, solo información.", minTrack: "mid" },
  { es: "action item", en: "action item", meaning: "Tarea concreta asignada.", minTrack: "junior" },
  { es: "blocker", en: "blocker", meaning: "Bloqueante.", minTrack: "junior" },
];

